[package]
name = "advent-of-code-2018-rs"
version = "0.1.0"
authors = ["BjÃ¶rn Westlin <bwestlin@gmail.com>"]

[dependencies]

[[bin]]
name = "day1"
path = "src/day1/day1.rs"

[[bin]]
name = "day2"
path = "src/day2/day2.rs"
